"""Modified codes to fit in their specific packages

Revision ID: 271a9b5d63c5
Revises: 97f81cf92c73
Create Date: 2026-09-11 13:23:16.518033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271a9b5d63c5'
down_revision: Union[str, Sequence[str], None] = '97f81cf92c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
