"""added body_temp to visit_logs for use in mobile APIs

Revision ID: 3980827cf050
Revises: 0003c0d56c4a
Create Date: 2026-09-07 20:10:00.789311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3980827cf050'
down_revision: Union[str, Sequence[str], None] = '0003c0d56c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
