"""testing whether we have a missing migration

Revision ID: 911fffd15f8f
Revises: 271a9b5d63c5
Create Date: 2026-09-16 16:10:34.074894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911fffd15f8f'
down_revision: Union[str, Sequence[str], None] = '271a9b5d63c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
