"""sync models to current schema

Revision ID: ced87c5d7877
Revises: 271a9b5d63c5
Create Date: 2026-09-19 10:55:24.447540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced87c5d7877'
down_revision: Union[str, Sequence[str], None] = 'ba14d18914a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index(op.f('ix_person_person_id'), 'person', ['person_id'], unique=False)
    op.create_table('system_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('target_person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_tokens_token_hash'), 'system_tokens', ['token_hash'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('person_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('email_attempted', sa.String(length=255), nullable=True),
    sa.Column('event_category', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_table('reset_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_otps_id'), 'reset_otps', ['id'], unique=False)
    op.create_table('supervisors',
    sa.Column('supervisor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('supervisor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_supervisors_supervisor_id'), 'supervisors', ['supervisor_id'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('raised_by_type', sa.String(length=20), nullable=True),
    sa.Column('raised_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=False)

    op.execute("DELETE FROM chvs")

    op.add_column('chvs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('chvs', sa.Column('certificate_number', sa.String(length=50), nullable=True))
    op.add_column('chvs', sa.Column('document_url', sa.String(length=500), nullable=True))
    op.add_column('chvs', sa.Column('certificate_status', sa.String(length=20), nullable=False))
    op.add_column('chvs', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.add_column('chvs', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chvs', sa.Column('rejection_notes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('chvs_email_key'), 'chvs', type_='unique')
    op.drop_constraint(op.f('chvs_phone_number_key'), 'chvs', type_='unique')
    op.create_unique_constraint(None, 'chvs', ['user_id'])
    op.create_foreign_key(None, 'chvs', 'supervisors', ['verified_by'], ['supervisor_id'])
    op.create_foreign_key(None, 'chvs', 'users', ['user_id'], ['user_id'])
    op.drop_column('chvs', 'is_active')
    op.drop_column('chvs', 'last_name')
    op.drop_column('chvs', 'hashed_password')
    op.drop_column('chvs', 'first_name')
    op.drop_column('chvs', 'phone_number')
    op.drop_column('chvs', 'email')
    op.add_column('mothers', sa.Column('person_id', sa.UUID(), nullable=False))
    op.alter_column('mothers', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'mothers', ['person_id'])
    op.create_foreign_key(None, 'mothers', 'person', ['person_id'], ['person_id'])
    op.drop_column('mothers', 'last_name')
    op.drop_column('mothers', 'phone_number')
    op.drop_column('mothers', 'first_name')
    op.drop_column('mothers', 'location_name')
    op.add_column('visit_logs', sa.Column('blood_sugar', sa.Float(), nullable=False, server_default='0'))
    op.add_column('visit_logs', sa.Column('body_temp', sa.Float(), nullable=False, server_default='37.0'))
    op.alter_column('visit_logs', 'blood_sugar', server_default=None)
    op.alter_column('visit_logs', 'body_temp', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_logs', 'body_temp')
    op.drop_column('visit_logs', 'blood_sugar')
    op.add_column('mothers', sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('mothers', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('mothers', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('mothers', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mothers', type_='foreignkey')
    op.drop_constraint(None, 'mothers', type_='unique')
    op.alter_column('mothers', 'date_of_birth',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('mothers', 'person_id')
    op.add_column('chvs', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('chvs', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('chvs', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('chvs', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('chvs', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('chvs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chvs', type_='foreignkey')
    op.drop_constraint(None, 'chvs', type_='foreignkey')
    op.drop_constraint(None, 'chvs', type_='unique')
    op.create_unique_constraint(op.f('chvs_phone_number_key'), 'chvs', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('chvs_email_key'), 'chvs', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('chvs', 'rejection_notes')
    op.drop_column('chvs', 'verified_at')
    op.drop_column('chvs', 'verified_by')
    op.drop_column('chvs', 'certificate_status')
    op.drop_column('chvs', 'document_url')
    op.drop_column('chvs', 'certificate_number')
    op.drop_column('chvs', 'user_id')
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_supervisors_supervisor_id'), table_name='supervisors')
    op.drop_table('supervisors')
    op.drop_index(op.f('ix_reset_otps_id'), table_name='reset_otps')
    op.drop_table('reset_otps')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_tokens_token_hash'), table_name='system_tokens')
    op.drop_table('system_tokens')
    op.drop_index(op.f('ix_person_person_id'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###